<%@ Page Language="C#" %>

<!DOCTYPE html>
<html>
<head>
    <title>Admin Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body style="background:#f5f5f5">

<form runat="server">

<div class="container" style="margin-top:50px">
    <div class="row mb-4">

<div class="col-md-3">
<div class="card text-center shadow">
<div class="card-body">
<h5>Add Company</h5>
<a href="placement_add.aspx" class="btn btn-primary">Open</a>
</div>
</div>
</div>

<div class="col-md-3">
<div class="card text-center shadow">
<div class="card-body">
<h5>View Placements</h5>
<a href="placement_display.aspx" class="btn btn-success">Open</a>
</div>
</div>
</div>

</div>
<h2 class="mb-4">Placement Officer Dashboard</h2>

<div class="card shadow">
    <div class="card-header bg-dark text-white">
        Contact Messages
    </div>

    <div class="card-body">

        <asp:GridView ID="GridView1" runat="server"
            AutoGenerateColumns="true"
            AutoGenerateDeleteButton="true"
            CssClass="table table-bordered"
            DataKeyNames="id"
            OnRowDeleting="DeleteRow">
        </asp:GridView>

    </div>
</div>

</div>

</form>

<script runat="server">

protected void Page_Load(object sender, EventArgs e)
{
    if (!IsPostBack)
    {
        LoadData();
    }
}

void LoadData()
{
    string cs = System.Configuration.ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;

    using (System.Data.SqlClient.SqlConnection con = new System.Data.SqlClient.SqlConnection(cs))
    {
        System.Data.SqlClient.SqlDataAdapter da =
        new System.Data.SqlClient.SqlDataAdapter("SELECT * FROM dbo.contact_messages ", con);

        System.Data.DataTable dt = new System.Data.DataTable();
        da.Fill(dt);

        GridView1.DataSource = dt;
        GridView1.DataBind();
    }
}

protected void DeleteRow(object sender, System.Web.UI.WebControls.GridViewDeleteEventArgs e)
{
    int id = Convert.ToInt32(GridView1.DataKeys[e.RowIndex].Value);

    string cs = System.Configuration.ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;

    using (System.Data.SqlClient.SqlConnection con = new System.Data.SqlClient.SqlConnection(cs))
    {
        System.Data.SqlClient.SqlCommand cmd =
        new System.Data.SqlClient.SqlCommand("DELETE FROM dbo.contact_messages WHERE id=@id", con);

        cmd.Parameters.AddWithValue("@id", id);

        con.Open();
        cmd.ExecuteNonQuery();
        con.Close();
    }

    LoadData();
}

</script>

</body>
</html>